version: '3.1'

services: 
  site:
    build: ./site
    ports: 
      - "8081:8080"
    links:
      - db
    volumes:
      - ./site:/usr/src/site
  db:
    image: mysql:5.7
    ports: 
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
