version: '3.1'

services:

  postgres11:
    image: postgres:11-alpine
    ports: 
      - '5433:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  
  postgres9:
    image: postgres:9-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sw_ships